source("load_data_from_source.R")
png(filename = "plot3.png", width = 480, height = 480)
plot(subdata$dt, subdata$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(subdata$dt, subdata$Sub_metering_2, type = "l", xlab = "", ylab = "Energy sub metering", col = "red")
points(subdata$dt, subdata$Sub_metering_3, type = "l", xlab = "", ylab = "Energy sub metering", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
